services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      # - JACKETT_API_KEY=${JACKETT_API_KEY}
      # - JACKETT_API_URL=${JACKETT_API_URL}
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
      - TZ=Asia/Kolkata
    volumes:
      - ./shared:/shared  # Shared directory for .env or other data
      - jackett_config:/config  # Share /config as a named volume
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9117"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped  

  bot:
    build:
      context: .
    container_name: mitsu-tg-indexer
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      jackett:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ./bot:/bot
      - ./shared:/shared  # Shared directory for .env or other data
      - jackett_config:/config  # Share /config as a named volume
      - config:/bot_config
    entrypoint: ["/shared/process_config.sh"]
    restart: unless-stopped

# Declare the shared volume
volumes:
  jackett_config:
  config:
