services:
  - name: jackett
    type: web
    env: docker
    docker:
      image: linuxserver/jackett:latest
      dockerfilePath: Dockerfile
      buildContext: .
      dockerCommand: /jackett --NoRestart
    plan: free
    branches: ["main", "dev"]
    healthCheckPath: /health
    maxShutdownDelaySeconds: 60
    envVars:
      - key: TZ
        value: Asia/Kolkata
      - key: PUID
        value: "1000"
      - key: PGID
        value: "1000"
    volumes:
      - /mnt/data/jackett/config:/config
      - /mnt/data/jackett/downloads:/downloads
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jackett"
      - "traefik.frontend.rule=Host:jackett.${DOMAINNAME}"
      - "traefik.docker.network=traefik_proxy"
    ports:
      - "9117:9117"
