services:
  - type: web
    name: jackett
    env: docker
    dockerfilePath: Dockerfile.jackett
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PUID
        value: "1000"
      - key: PGID
        value: "1000"
      - key: AUTO_UPDATE
        value: "true"
      - key: RUN_OPTS
        value: ""
      - key: TZ
        value: "Asia/Kolkata"
    ports:
      - port: 9117
    disk:
      name: jackett_config
      mountPath: /config

  - type: web
    name: mitsu-tg-indexer
    env: docker
    dockerfilePath: Dockerfile.bot
    plan: free
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromDotEnv: TELEGRAM_BOT_TOKEN
    startCommand: "/shared/process_config.sh"
    dependsOn:
      - name: jackett
        required: true
    ports:
      - port: 5000
    disk:
      name: config
      mountPath: /bot_config
