services:
  - type: web
    name: jackett-indexer-api
    env: docker
    dockerfilePath: Dockerfile.jackett
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PUID
        value: "1000"
      - key: PGID
        value: "1000"
      - key: AUTO_UPDATE
        value: "true"
      - key: RUN_OPTS
        value: ""
      - key: TZ
        value: "Asia/Kolkata"

  - type: worker
    name: mitsu-tg-bot
    env: docker
    dockerfilePath: Dockerfile.bot
    plan: free
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # Will use the Render dashboard value
      - key: JACKETT_API_URL
        sync: false  # Will use the Render dashboard value
      - key: JACKETT_API_KEY
        sync: false  # Will use the Render dashboard value
