name: Docker Multi-Container Scheduler

on:
  schedule:
    - cron: '0 3 * * *'  # Start containers at 3:00 AM UTC
    - cron: '30 15 * * *'  # Stop containers at 3:30 PM UTC

jobs:
  start-docker-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Docker Environment
        run: |
          docker --version
          docker compose version

      - name: Start containers
        run: |
          docker compose up -d

  stop-docker-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Docker Environment
        run: |
          docker --version
          docker compose version

      - name: Stop containers
        run: |
          docker compose down
