name: Docker Multi-Container Scheduler

on:
  schedule:
    # Start the containers at 3:00 AM UTC/8:30 AM IST daily
    - cron: '0 3 * * *'
    # Stop the containers at 3:30 PM/8:00 PM IST daily
    - cron: '30 15 * * *'

jobs:
  start-docker-containers:
    if: github.event.schedule == '0 3 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start containers
        run: |
          docker-compose up -d

  stop-docker-containers:
    if: github.event.schedule == '30 15 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Stop containers
        run: |
          docker-compose down
